### ISSUE TITLE
GeSellActivity - Opens thee GE intead of the bank?

### ISSUE THREAD

**Issue by Azn2000** [Explv/Explvs-AIO#55]
For me it looked like the Task sometimes will open the GE instead of the Bank,
also sometimes the Task is to fast with withdrawing items, so they will not be in the inventory

**Comment by Explv** [comment]
I have added extra sleeps to the banking, that should hopefully solve your "too fast" issue.

I haven't noticed the bot opening the GE instead of the bank. I did notice some issues today regarding the bot detecting if the Grand Exchange is open. Looks like the OSBot API `GrandExchange.isOpen` function is no longer working. I have a pushed a fix for that, so maybe you could try again and let me know if this is still an issue?

**Comment by Explv** [comment]
Fixed in https://github.com/Explv/Explvs-AIO/commit/4cf4e575445a0569ec23b6c4f888e0ef30783bd5
